name: Quasar Electron Build and Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-capacitor:
    if: github.event.pull_request.merged == true

    runs-on: ${{ matrix.os-versions }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os-versions: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Hello world action step
        id: get_version
        uses: txkodo/MyTestAction@v1

      - name: Setup NodeJS Environment 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn build

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: Automated Electron Deployment
          draft: false
          prerelease: false

      - name: Upload a Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/electron/Packaged/gha ${{steps.get_version.outputs.version}}.msi
          asset_name: gha-${{steps.get_version.outputs.version}}.msi
          asset_content_type: appliction/msi
