name: Build

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch

jobs:
  create-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Build and Daploy
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull
          yarn install
          yarn build
          yarn deploy
